### ISSUE TITLE
suspend

### ISSUE THREAD

**Issue by Axlefublr** [guyfedwards/nom#107]
I've searched through PRs and issues, didn't find this

I suspend (ctrl+z) a lot, and would love for nom to support it! Currently it doesn't react

As a maintainer I know it's not very exciting to work on a feature you (might) see as useless, so lemme draw out my workflow to show why suspending is beneficial

I'm going through my RSS feed of [terminaltrove](https://terminaltrove.com) and see a TUI that I want to try immediately. \
I (in theory) suspend nom, letting it keep all of its state; install that other tui program and try it out. \
After spending some time with it, I come back to nom using `fg` and continue on reading from the same exact spot
> "You could just close and reopen it?"

Isn't as good because once I reopen, I need to re-gain the state that I had. I need to go back to the article I was reading and open it again. Arguably that's not that much effort, but suspending lets me put in *no* effort, which is great UX. \
Also, maybe nom is currently doing a refresh; with the close and reopen method, it's in my best interest to wait for it to finish refreshing and *then* close, so that introduces another slowdown that suspending wouldn't

**Comment by guyfedwards** [comment]
Interesting, nom is probably catching the keypress and not passing it through. Agree we should support it as it's a pretty standard feature in shells.
