### ISSUE TITLE
Add option to preview/browse rss feed without adding to config

### ISSUE THREAD

**Issue by williamla** [guyfedwards/nom#13]
`--preview <feed url>`

**Comment by guyfedwards** [comment]
What content woudl this show? Are you thinking the list of entries from that feed? If so we can add a `--feeds` flag which overrides the feeds in config.yml.

**Comment by williamla** [comment]
Yes, exactly.

**Comment by guyfedwards** [comment]
Makes sense, I had planned to add `--feeds` for the same sort of reasons.

**Comment by guyfedwards** [comment]
Addresssed in https://github.com/guyfedwards/nom/releases/tag/v1.1.6
