### ISSUE TITLE
Some feeds cause panic

### ISSUE THREAD

**Issue by CondensedMilk7** [guyfedwards/nom#22]
Some feeds I've tested cause panic with this output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc6941]

goroutine 9 [running]:
github.com/guyfedwards/nom/internal/rss.Fetch({0xc0003bb080, 0x20})
	/home/pt/go/pkg/mod/github.com/guyfedwards/nom@v1.1.3/internal/rss/main.go:80 +0x341
github.com/guyfedwards/nom/internal/commands.fetchFeed(0x0?, 0x0?, {0xc0003bb080, 0x20})
	/home/pt/go/pkg/mod/github.com/guyfedwards/nom@v1.1.3/internal/commands/main.go:149 +0x86
created by github.com/guyfedwards/nom/internal/commands.Commands.fetchAllFeeds
	/home/pt/go/pkg/mod/github.com/guyfedwards/nom@v1.1.3/internal/commands/main.go:112 +0x46f
```

The URLs that cause the same issues are the following:
- https://primordialsoup.info/feed
- https://11ty.rocks/feed
- https://www.11ty.dev/blog/feed.xml

One piece of information that might be useful is that they are all built with Eleventy and are hosted on Netlify. The URL pointing to the feed XML file is handled by Netlify's "redirect" function that is specified in `netlify.toml` file. I think they are also technically Atom feeds.

**Comment by guyfedwards** [comment]
Interesting, thanks for the report, will take a look

**Comment by CondensedMilk7** [comment]
I have opened a PR #23. Looks like some feeds just don't have fields besides the bare minimum (title and link) so I think it can be ignored if they are missing.
