### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by guyfedwards** [guyfedwards/nom#4]
> Newsboat does a lot but I've not worked out how to show tagged/starred articles by category, only by feed... Would love that feature and the ability to sync with Tiny Tiny RSS...

Add searching by text in list, also by source, category. 

Options:
- `foo` narrows by title
- `foo category:allfoos` narrows by title within category

**Comment by guyfedwards** [comment]
Filtering by title added in #v2.0.0

**Comment by kanielrkirby** [comment]
@guyfedwards I'd love to help contribute this feature (namely, the filtering by feed name), as I use `nom` quite often.

Some thoughts I'd like to run by you. Glancing through the code for `charmbracelet/bubbles/list`, it seems that the main way I could see this working is by overriding the default `FilterFunc` on the `list`. For example:

```go
func CustomFilter(term string, targets []string) []list.Rank {
      // split term into FeedName and Title, exclude targets that don't include FeedName

/*    This is the default code, copied from bubbles/list
	ranks := fuzzy.Find(term, targets)
	sort.Stable(ranks)
	result := make([]list.Rank, len(ranks))
	for i, r := range ranks {
		result[i] = list.Rank{
			Index:          r.Index,
			MatchedIndexes: r.MatchedIndexes,
		}
	}
*/

	return result
}

// in initialization
l := list.New()
l.Filter = CustomFilter
```

And then changing the `TUIItem.FilterValue()` to also include the string for the FeedName:

```go
func (i TUIItem) FilterValue() { return i.FeedName + "some_delimiter" + i.Title }
```

This is using the standard `bubbles/list` functionality. I'd definitely like to hear your thoughts on this, and if there are any other filters you really want to add, or if you'd like this to be the primary one.

Thanks for all your hard work!

**Comment by guyfedwards** [comment]
Hey @kanielrkirby, yea that's along the same lines I was thinking. Would be happy to review anything if you want to implement. 

The initial functionality can just be a text search and later down the line add categories etc once the core function is fleshed out.
