### ISSUE TITLE
nom got merged into nixpkgs

### ISSUE THREAD

**Issue by nadir-ishiguro** [guyfedwards/nom#44]
Hey, just wanted to inform you that nom just got merged into the nix package repository:

https://github.com/NixOS/nixpkgs/pull/266742

Thought you might like to know that people are using it and didn't know how else to contact you.

**Comment by guyfedwards** [comment]
Nice one thanks @nadir-ishiguro

**Comment by guyfedwards** [comment]
@nadir-ishiguro v2.0.5 has just released with fixes for cross platform binaries, not sure if you need to update stuff in the nix package repo or how versioning works there?

**Comment by nadir-ishiguro** [comment]
I'll update it, thanks for the headsup.
