### ISSUE TITLE
inconsistent date/time parsing/formatting

### ISSUE THREAD

**Issue by guyfedwards** [guyfedwards/nom#47]
> date/time not always recognised (shows 0001-01-01 00:00:00 +0000 UTC for [this sample feed](https://thecyberwire.com/feeds/rss.xml))

from https://github.com/guyfedwards/nom/issues/42

**Comment by emilwidlund** [comment]
@guyfedwards Love this project! I just pledged $50 on behalf of our team at Polar. Feel free to claim it over at https://polar.sh :)

**Comment by guyfedwards** [comment]
fixed in https://github.com/guyfedwards/nom/commit/719f5d9ac324db3ae7d34d5cf5c695fa9e932823

**Comment by guyfedwards** [comment]
@emilwidlund Thanks for this, I've just been looking at the polar platform, is there a way to backdate the commit linking?
