### ISSUE TITLE
`go install` would install v1.2.1 nom

### ISSUE THREAD

**Issue by Adios** [guyfedwards/nom#51]
I installed nom by
```
go install github.com/guyfedwards/nom/cmd/nom@latest
```
but it would only build the latest version in v1.

And the latest version on https://pkg.go.dev/github.com/guyfedwards/nom is also v.1.2.1.

Maybe some go enforced v1/v2 problems?

--
I am on `go version go1.21.5 darwin/amd64`

**Comment by guyfedwards** [comment]
Interesting, it's possible that the module proxy has an old version but can't investigate currently. Until I can look into it you should be able to install a version directly from the releases https://github.com/guyfedwards/nom/releases

**Comment by guyfedwards** [comment]
This should be fixed as part of #55. Closing
