### ISSUE TITLE
module URL should be github.com/guyfedwards/nom/v2 for Golang servers to pick it up

### ISSUE THREAD

**Issue by yurivict** [guyfedwards/nom#54]
[here](https://github.com/guyfedwards/nom/blob/master/go.mod#L1)

**Comment by guyfedwards** [comment]
Thanks for reporting, related to https://github.com/guyfedwards/nom/issues/51

**Comment by yurivict** [comment]
Yes. On FreeBSD we use Golang servers to fetch sources of Go ports, and this is only possible for Go projects compliant with the /vN requirement - when the URL has the suffix /vN, where N is the major version of the project when N>=2.

Fixing this would enable us to create the FreeBSD port for nom.

**Comment by guyfedwards** [comment]
Thanks for the info. I just released https://github.com/guyfedwards/nom/releases/tag/v2.1.2, can you check this works as expected?
