### ISSUE TITLE
cannot get fresh rss to work at all. 

### ISSUE THREAD

**Issue by legolasdimir** [guyfedwards/nom#57]
I am running on windows and I have tried to set this up in %LOCALAPPDATA% but I don't know which fresh RSS API this is supposed to use and every option I try from the help just makes it show the help again. Can I get some guidance?

**Comment by guyfedwards** [comment]
@legolasdimir could you share your config file? (Redact the various pieces)

**Comment by legolasdimir** [comment]
![image](https://github.com/guyfedwards/nom/assets/21345773/3f7c0430-d8d7-44f7-86cd-15f2e8d5c019)

Also can you tell me what API it uses for freshrss? I couldnt find anything there as to wether it uses fever or g reader.

Im not sure WHICH commands I should be running.

I have tried to run the following command:
`nom /config-path 'C:\Users\bryan.pruett\AppData\Local\nom\config.yml'`

And this is what happens

![image](https://github.com/guyfedwards/nom/assets/21345773/f718256b-6809-4158-af99-3f5b6631ebe5)

**Comment by guyfedwards** [comment]
Config looks good. `nom` uses the greader api for FreshRSS.

If everything is working, you should jsut need to run `nom` for the TUI to start. I suspect you have an error that is being hidden. Can you try with the `--verbose` (or windows /verbose?) flag to add logging.

**Comment by guyfedwards** [comment]
You could also try running `nom list`, this will show a list of feeds without a TUI

**Comment by legolasdimir** [comment]
All of those options only show the help dialogue. I realize now I did not
mention that I am running this on windows.

[image: image.png]

**Comment by guyfedwards** [comment]
Unfortunately I don't develop on windows so can't test this. Running with `--verbose` is the best way to see an error, otherwise would try compiling from source.
