### ISSUE TITLE
Installation fails on M3 MacBook running macOS Sonoma 14.4

### ISSUE THREAD

**Issue by realbaylen** [guyfedwards/nom#58]
`$ go install github.com/guyfedwards/nom/cmd/nom@latest
`

This command takes a few seconds to run, provides no output, and does not seem to succeed in installing `nom`.

The output of `$ go version` is `go version go1.22.1 darwin/arm64`.

**Comment by guyfedwards** [comment]
Can you try running with `go install -v -n -a github.com/guyfedwards/nom/cmd/nom@latest `. This should provide more logging on why the install is failing.

**Comment by guyfedwards** [comment]
I've just tried the `go install ...` command in a fresh linux env and it worked but installed an old version. I might suggest that you are better off downlaoding one of the binaries from [releases](https://github.com/guyfedwards/nom/releases) instead of `go install ...`

**Comment by guyfedwards** [comment]
closing as no reply
