### ISSUE TITLE
Bug : http error: 403 Blocked reddit

### ISSUE THREAD

**Issue by oppZ** [guyfedwards/nom#77]
I tried to add the reddit rss by using the following command : 
~/Downloads/nom_2.2.3_linux_amd64$ ./nom -f https://www.reddit.com/r/linux/.rss
but I got the following : 
Error fetching https://www.reddit.com/r/linux/.rss: rss.Fetch: http error: 403 Blocked

I'm on ubuntu 24.04. I don't if it matters, but I'm using cellular network. Although through Firefox I get the .rss file so I don't know

![image](https://github.com/guyfedwards/nom/assets/28532065/78baa20c-0f63-43ed-ad73-8566298924b1)

**Comment by oppZ** [comment]
no vpn but cellular network, and yes i could access the rss url in browser

**Comment by guyfedwards** [comment]
@oppZ could you try this release: https://github.com/guyfedwards/nom/releases/tag/v2.3.1-beta

I fixed it on my machine but would be good to confirm it on someone elses
.

**Comment by oppZ** [comment]
I can confirm that now i can access the reddit rss flow. Is is normal that I can't nom add anymore?

**Comment by guyfedwards** [comment]
Ah so if there was an error with the add it just shows help? Do you know what was the issue when you were trying to add/how you got it to work?

**Comment by oppZ** [comment]
If the url is already in the config file, it will show help

**Comment by guyfedwards** [comment]
nice catch, opened https://github.com/guyfedwards/nom/issues/81 to address.

**Comment by guyfedwards** [comment]
Fixed in https://github.com/guyfedwards/nom/releases/tag/v2.4.0

**Comment by janiosarmento** [comment]
I'm sorry to have to tell you, but on 2.8.0, I can't access Reddit feeds. Perhaps we need a setting for a custom user-agent string?
