### ISSUE TITLE
Open links in browser 

### ISSUE THREAD

**Issue by guyfedwards** [guyfedwards/nom#8]
Add ability to open (maybe also mouse support?) for links within an article

**Comment by p5quared** [comment]
> In newsboat all links are followed by a [x] thing, where x is a number and at the very bottom of the article there's a section like the following:
> 
> [1] _first link in the article url_ [2] _second link in the article url_
> 
> In newsboat you can configure a key where after pressing it inside an article it will prompt you for a number and after specifying which number/link you meant it opens it in a web browser.

What do you think of the Newsboat approach mentioned in #34?
A simple <key><#> to open any links; and just add an annotation for each link that is rendered.

Some sort of popup modal seems like overkill.

**Comment by guyfedwards** [comment]
Yea I think that seems like a good solution. It generally seems that newsboat has a lot of good UX features so can worth building on them. Unsure about the best ui for it, probably a panel up from the bottom with list of links and the numbers that can then be selected by typing the desired link number., similar to how the `? help` panel appears currently

**Comment by p5quared** [comment]
What about supporting two options?
For example:
* `o + <#>` opens a link with annotation [#](haven't looked enough into bubbletea but I'd imagine there's a way to register multi-key inputs)

* `O` opens list of all links, and then press some <#> to open a specific link?

**Comment by guyfedwards** [comment]
Yea those seem like solid sugggestions, would welcome the contribution. 

One thing to note on the opening aspect is not to rely on `xdg-open` being on the system and so perhaps defaulting to `xdg-open` but allowigin a config option for overriding with another binary would be good.
